spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.0.109/member_manage?autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: Chenye123
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

server:
  port: 8080

#jwt
jwt:
  header: token
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒
  token-validity-in-seconds: 14400000


tencent:
  sms:
    #腾讯云短信服务参数
    #腾讯云账户secretId，secretKey
    secretId: AKIDTq3e3FErFVZPyMakngOwSgt2lMqCII9s
    secretKey: nRwIW7qSvFQPCmBPQDpJchZHm6C4jBPV
    #短信签名内容: 使用 UTF-8 编码，必须填写已审核通过的签名
    signName: '盛唐Dev个人公众号'
    #短信应用ID: 短信SdkAppId在 [短信控制台] 添加应用后生成的实际SdkAppId
    sdkAppId: 1400837331
    #模板 ID: 必须填写已审核通过的模板 ID
    templateId: 1858174

mybatis-plus:
  mapper-locations: classpath*:com/wechat/mapper/xml/*.xml
  type-aliases-package: com.wechat.entity

management:
  server:
    port: 8081
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
    health:
      show-details: always