spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.0.109/member_manage?autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  port: 8080

service:
  url: http://127.0.0.1:8080/file

java:
  awt:
    headless: true

#jwt
jwt:
  header: token
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  base64-secret: MTIzNDU2Nzg5MHF3ZXJ0eXVpb3Bhc2RmZ2hqa2x6eGN2Ym5t
  # 令牌过期时间 25天 此处单位/毫秒
  token-validity-in-seconds: 2160000000


tencent:
  sms:
    #腾讯云短信服务参数
    #腾讯云账户secretId，secretKey
    secretId: 123
    secretKey: 123
    #短信签名内容: 使用 UTF-8 编码，必须填写已审核通过的签名
    signName: '陕西盛放御选餐饮'
    #短信应用ID: 短信SdkAppId在 [短信控制台] 添加应用后生成的实际SdkAppId
    sdkAppId: 1400837331
    #模板 ID: 必须填写已审核通过的模板 ID
    templateId: 1858174

mybatis-plus:
  mapper-locations: classpath*:com/wechat/mapper/xml/*.xml
  type-aliases-package: com.wechat.entity

logging:
  level:
    com.wechat.mapper: DEBUG
  file:
    path: ./logs/

management:
  server:
    port: 8081
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
    health:
      show-details: always